#!/bin/bash
# init-env.sh - Runs on HOST before containers start
# Creates .env file for docker-compose with appropriate URLs
# AND pre-initializes project directory for backend container

set -euo pipefail

# Semiont version to use for all artifacts
SEMIONT_VERSION="0.2.35"

# Helper for timestamped logging
log() {
    echo "[$(date '+%H:%M:%S')] $1"
}

cd "$(dirname "$0")"

log "Starting init-env.sh (Semiont version: $SEMIONT_VERSION)"

# Check if running in Codespaces
if [ -n "${CODESPACE_NAME:-}" ]; then
    log "Detected Codespaces environment: ${CODESPACE_NAME}"

    # Use Envoy port 8080 for all public-facing URLs
    ENVOY_URL="https://${CODESPACE_NAME}-8080.app.github.dev"
    SITE_DOMAIN="${CODESPACE_NAME}-8080.app.github.dev"

    cat > .env <<EOF
# Codespaces URLs (generated by init-env.sh)
# All browser traffic goes through Envoy on port 8080
SEMIONT_VERSION=${SEMIONT_VERSION}
NEXT_PUBLIC_API_URL=${ENVOY_URL}
NEXTAUTH_URL=${ENVOY_URL}
NEXT_PUBLIC_SITE_NAME=Semiont Demo
NEXT_PUBLIC_OAUTH_ALLOWED_DOMAINS=${SITE_DOMAIN}
EOF

    log "Created .env with Codespaces Envoy URLs (port 8080)"
else
    log "Local environment detected"

    # Use Envoy port 8080 for all public-facing URLs
    ENVOY_URL="http://localhost:8080"
    SITE_DOMAIN="localhost:8080"

    # Create .env with localhost Envoy URLs
    cat > .env <<EOF
# Local URLs (generated by init-env.sh)
# All browser traffic goes through Envoy on port 8080
SEMIONT_VERSION=${SEMIONT_VERSION}
NEXT_PUBLIC_API_URL=http://localhost:8080
NEXTAUTH_URL=http://localhost:8080
NEXT_PUBLIC_SITE_NAME=Semiont Demo
NEXT_PUBLIC_OAUTH_ALLOWED_DOMAINS=
EOF

    log "Created .env with localhost Envoy URLs (port 8080)"
fi

# Install @semiont/cli globally to get 'semiont' command
log "Installing @semiont/cli@$SEMIONT_VERSION..."
log "  Cleaning npm cache..."
npm cache clean --force 2>&1 | head -5 || true
log "  Cache cleaned, installing package..."
npm install -g @semiont/cli@$SEMIONT_VERSION --registry https://registry.npmjs.org/ --legacy-peer-deps 2>&1 | grep -v "npm warn" || true

# Show the package version from npm
SEMIONT_PACKAGE_VERSION=$(npm list -g @semiont/cli --depth=0 2>/dev/null | grep @semiont/cli | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "unknown")
log "  ✓ Package installed: @semiont/cli@$SEMIONT_PACKAGE_VERSION"

# Try to run the CLI to get its reported version
SEMIONT_CLI_VERSION=$(semiont --version 2>&1 | head -1 || echo "CLI command failed")
log "  CLI version output: $SEMIONT_CLI_VERSION"

# Pre-initialize project directory for backend container
# This must happen BEFORE docker-compose starts the backend
log "Initializing project directory for backend container..."

PROJECT_DIR="../project"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

# Run semiont init to create initial project structure
log "Running semiont init..."
semiont init --force 2>&1 || {
    log "  ✗ semiont init failed - check logs above"
    exit 1
}
log "  ✓ Project initialized with semiont init"

# Overwrite with our templates
log "Copying configuration templates..."
cp ../.devcontainer/semiont.json semiont.json
cp ../.devcontainer/environments-demo.json environments/demo.json
log "  ✓ Templates copied"

# Update URLs in demo.json for the detected environment
if [ -n "${CODESPACE_NAME:-}" ]; then
    log "Updating Codespaces URLs in configuration..."

    # For Codespaces, we also need direct frontend URL for internal config
    FRONTEND_DIRECT_URL="https://${CODESPACE_NAME}-3000.app.github.dev"

    node -e "
    const fs = require('fs');
    const baseConfig = JSON.parse(fs.readFileSync('semiont.json', 'utf-8'));
    const envFile = 'environments/demo.json';
    const config = JSON.parse(fs.readFileSync(envFile, 'utf-8'));
    config.site.domain = '${SITE_DOMAIN}';
    config.site.oauthAllowedDomains = ['${SITE_DOMAIN}', ...(baseConfig.site?.oauthAllowedDomains || [])];
    config.services.frontend.url = '${FRONTEND_DIRECT_URL}';
    config.services.frontend.publicURL = '${ENVOY_URL}';
    config.services.frontend.allowedOrigins = ['${SITE_DOMAIN}'];
    config.services.backend.publicURL = '${ENVOY_URL}';
    config.services.backend.corsOrigin = '${ENVOY_URL}';
    fs.writeFileSync(envFile, JSON.stringify(config, null, 2));
    "
    log "  ✓ URLs configured for Codespaces"
fi

cd ../.devcontainer
log "✓ Project directory initialized at $PROJECT_DIR"
log "init-env.sh completed successfully"
